---
- name: Test task
  hosts: servers
  become: true
  tasks:
    - name: "install docker"
      apt:
        name: docker
        state: latest
        update_cache: yes
      service:
        name: docker
        state: restarted
