# Use the official Python image from the Docker Hub
FROM python:3.8.2

# These two environment variables prevent __pycache__/ files.
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

# Make a new directory to put our code in.
RUN mkdir /mysite

# Change the working directory.
# Every command after this will be run from the /code directory.
WORKDIR /mysite

# Copy the requirements.txt file.
COPY ./requirements.txt /mysite/

# Upgrade pip
RUN pip install --upgrade pip

# Install the requirements.
RUN pip install -r requirements.txt

# Copy the rest of the code.
COPY . /mysite/

RUN apt-get update && apt-get install -y netcat

ENTRYPOINT ["/mysite/djangoproject/entrypoint.sh"]